name: CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.18.0'

      - name: Install dependencies
        run: |
          cd frontend  
          npm install
          cd ../backend  
          npm install

      - name: Install pm2
        run: |
          npm install pm2 -g

      - name: Start Node.js Server (Backend)
        run: |
          cd backend
          npm run start:prod &

      - name: Start React App (Frontend)
        run: |
          cd frontend
          npm run dev &

      - name: Install ngrok
        run: |
          npm install -g ngrok
          ngrok config add-authtoken 2sLFXEKSbOjAQCGoxXlqRQVvxm1_5Twgq6Ncv3KsSfQU5smhR

      - name: Start Ngrok Tunnels for Both Frontend and Backend
        run: |
          ngrok http 5173 --name frontend & 
          ngrok http 5173 --name backend &

      - name: Wait for apps to start
        run: |
          sleep 10

      - name: Check if React app is running
        run: |
          curl --fail http://localhost:5173 || exit 1

      - name: Display URLs for React App and Backend API
        run: |
          echo "React app should be running at: http://localhost:5173"
          echo "Backend API should be running at: http://localhost:3000"
          for i in {1..10}; do
            ngrok_url_frontend=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
            ngrok_url_backend=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[1].public_url)
            if [ "$ngrok_url_frontend" != "null" ] && [ "$ngrok_url_backend" != "null" ]; then
              break
            fi
            echo "Waiting for ngrok URLs..."
            sleep 5
          done
          echo "Access React app at ngrok URL: $ngrok_url_frontend"
          echo "Access Backend API at ngrok URL: $ngrok_url_backend"

      - name: Keep apps running for 600 seconds
        run: |
          sleep 600
