name: CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.18.0'

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install
          npm rebuild better-sqlite3
          
      - name: Rebuild bcrypt package
        run: |
            cd backend
            npm rebuild bcrypt

      - name: Install pm2
        run: |
          npm install pm2 -g

      - name: Start Node.js Server (Backend) on port 8081
        run: |
          cd backend
          nohup npm run start:prod &  # or use a custom command to start the backend server

      - name: Start React App (Frontend) on port 5173
        run: |
          cd frontend
          nohup npm run dev &  # Start React app on port 5173

      - name: Install ngrok
        run: |
          npm install -g ngrok
          ngrok config add-authtoken 2sLFXEKSbOjAQCGoxXlqRQVvxm1_5Twgq6Ncv3KsSfQU5smhR

      - name: Start ngrok Tunnel (One Tunnel for Both Frontend and Backend)
        run: |
          # Expose frontend on port 5173
          ngrok http 5173 --host-header=localhost:5173 --log=stdout &  # Frontend tunnel
          # Expose backend on port 8081
          ngrok http 8081 --host-header=localhost:8081 --log=stdout &  # Backend tunnel

      - name: Wait for ngrok tunnels to initialize
        run: |
          # Wait for a longer time to ensure ngrok tunnels are initialized
          sleep 20

      - name: Fetch ngrok Tunnel URLs
        run: |
          # Fetch ngrok tunnel URLs using the API
          ngrok_url_frontend=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          ngrok_url_backend=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[1].public_url')

          echo "Frontend is available at: $ngrok_url_frontend"
          echo "Backend API is available at: $ngrok_url_backend"

      - name: Display URLs for React App and Backend
        run: |
          echo "Access React app at: $ngrok_url_frontend"
          echo "Access Backend API at: $ngrok_url_backend"

      - name: Keep apps running for 600 seconds
        run: |
          sleep 600
