name: CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.18.0'

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install
          npm rebuild better-sqlite3
          
      - name: Rebuild bcrypt package
        run: |
            cd backend
            npm install bcryptjs

      - name: Install pm2
        run: |
          npm install pm2 -g

      - name: Start Node.js Server (Backend) on port 8081
        run: |
          cd backend
          nohup npm run start:prod &  # Start the backend server on port 8081

      - name: Install ngrok
        run: |
          npm install -g ngrok
          ngrok config add-authtoken 2sLFXEKSbOjAQCGoxXlqRQVvxm1_5Twgq6Ncv3KsSfQU5smhR

      - name: Start ngrok Tunnel for Frontend
        run: |
          cd frontend
          # Expose frontend on port 5173 via ngrok (only frontend exposed)
          ngrok http 5173 --host-header=localhost:5173 --log=stdout &

      - name: Wait for ngrok tunnel to initialize
        run: |
          # Wait for a longer time to ensure ngrok tunnels are initialized
          sleep 20

      - name: Fetch ngrok Tunnel URL
        run: |
          # Fetch the ngrok tunnel URL for frontend
          ngrok_url_frontend=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Frontend is available at: $ngrok_url_frontend"

      - name: Display URL for React App
        run: |
          echo "Access React app at: $ngrok_url_frontend"
          # Backend URL is not needed since it's running locally

      - name: Keep frontend running for 600 seconds
        run: |
          sleep 600
